# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5.2.0
_src_path: https://github.com/epics-containers/services-template-helm
athena_services: []
cluster_name: argus
cluster_namespace: kgv66629
description: t01 IOC Instances and Services
domain: t01
gateway: false
git_platform: github.com
location: bl01t
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
