# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/4.2.0/ioc-instance.schema.json

ioc-instance:
  image: ghcr.io/diamondlightsource/fastcs-thorlabs-mff:latest
  startCommand: fastcs-thorlabs-mff
  startArgs:
    - run
    - /epics/ioc/config/controller.yaml
  liveness: ["exit", "0"]
  stop: ["exit", "0"]
