# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/4.2.0/ioc-instance.schema.json

ioc-instance:
  image: ghcr.io/diamondlightsource/fastcs-thorlabs-mff:0.1.2
  command:
    - fastcs-thorlabs-mff
  args:
    - run
    - /epics/ioc/config/controller.yaml
  livenessExecutable: ""
  preStopExecutable: ""
